### ISSUE TITLE
libxcb-icccm missing

### ISSUE THREAD

**Issue by ATW136** [blueprint-freespeech/ricochet-refresh#120] opened 2021-08-27 20:38 UTC
Debian Testing (after Bullseye release)

Download:  ricochet-refresh-3.0.10-linux-x86_64.tar

During execution of ./ricochet-refresh, libxcb-icccm.so:4 could not be opened. Missing.

Executed apt install torbrowser-launcher.

Can now use ricochet-refresh.

ATW

**Comment by pospeselr** [comment] 2021-10-03 15:39
The fix here is to install libxcb-icccm4 (presumably torbrowser-launcher pull that down). Our next release in the coming weeks will include a .deb which should hopefully take care of this automatically on debian-baed systems.

**Comment by pospeselr** [comment] 2021-10-03 16:33
Duplicate of #23

**Closed by pospeselr** 2021-10-03 16:33 UTC
Labels: bug, duplicate, build
